[package]
name = "ComposableToken"
version = "0.2.0"
authors = ["lay (Aladeen)"]

[addresses]
# composable_token = "0xd758b832d4d8fcad58ac7363a6b87af342a6e0dfd25897aa65233c606526e8f4"
# testnet
composable_token = "0x5fe4421182921f3f4c847bb30127e25138ef463455c5981e7726fa08ce42855e"

[dev-addresses]

[dependencies.TokenMinter]
local = "./TokenMinter"

[dev-dependencies]

