[package]
name = "ComposableToken"
version = "0.2.0"
authors = ["lay (Aladeen)"]

[addresses]
composable_token = "0xd758b832d4d8fcad58ac7363a6b87af342a6e0dfd25897aa65233c606526e8f4"

[dev-addresses]

[dependencies.TokenMinter]
local = "./TokenMinter"

[dev-dependencies]

